# Generated by Django 2.2.1 on 2019-05-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='many_to_many_mapping_proj_person',
            new_name='many_to_many_mapping_proj_user',
        ),
        migrations.RenameField(
            model_name='project_user',
            old_name='Person_id',
            new_name='User_id',
        ),
        migrations.AlterField(
            model_name='project_user',
            name='IsMentor',
            field=models.BooleanField(default=False),
        ),
    ]
    atomic = False
