# Generated by Django 2.2.1 on 2019-05-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190523_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_user_list', models.TextField()),
            ],
        ),
    ]
